name: Test

parameters:
  - name: Boolean
    type: boolean
    default: false
  - name: String
    type: string
    default: sample text

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.x'
#     addToPath: true

- script: |
    apt-get update
    apt-get install -y curl jq
    pwd
    ls
    ./createTask/del.sh
#     pip install requests
#   displayName: 'Install Python dependencies'

# - script: |
#     python create_work_item.py
#   env:
#     ORG_NAME: $(ORG_NAME)
#     PROJECT_NAME: $(PROJECT_NAME)
#     AZURE_DEVOPS_PAT: $(ACCESS_TOKEN)
#   displayName: 'Run Python Script'
