name: Create Task

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    ls
    sudo apt-get update
    sudo apt-get install -y curl
    sudo apt-get install -y jq
    /bin/bash ./createTask/del.sh
  displayName: 'execute'

# - script: |
#     pip install -r ./createTask/requirements.txt
#     python ./createTask/create_task.py
#   env:
#     ORG_NAME: takurou76
#     PROJECT_NAME: az-learn
#     AZURE_DEVOPS_PAT: OjljVGN1THFZMlppckx3ZUR2Y2xIdVlWYUg2eENvQnMyQ2RJeFlGTGltOXlDMFpPWjRRQ09KUVFKOTlCREFDQUFBQUFBQUFBQUFBQVNBWkRPNGFpUw==
#   displayName: 'execute'
